Update books.md
Universidade-Livre/ciencia-da-computacao pull request #62
Opened 2023-04-20 12:41 UTC by italo-mauricio

Uma proposta de 15 livros sobre computação e programação no geral.

2023-05-04 17:45 UTC, jeffque approved these changes
Ótimas sugestões, @italo-mauricio !

Eu acho que ficaria mais amigável se a gente usasse mais markdown e menos html, se me permite posso abrir um PR para o teu branch local.

E também acho que esses livros não tem precedência perante o outro, então uma listagem simples ficaria bacana.

Em markdown os 3 primeiros ficariam assim:

```md
- Entendendo Algoritmos: Um Guia Ilustrado Para Programadores e Outros Curiosos. À venda na [Amazon](https://www.amazon.com.br/Entendendo-Algoritmos-Ilustrado-Programadores-Curiosos/dp/8575225634)
- Algoritmos - Teoria e Prática. À venda na [Amazon](https://www.amazon.com.br/Algoritmos-Teoria-Pr%C3%A1tica-Thomas-Cormen/dp/8535236996/ref=asc_df_8535236996/?tag=googleshopp00-20&linkCode=df0&hvadid=379707181411&hvpos=&hvnetw=g&hvrand=13813726138626692774&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9047717&hvtargid=pla-1002925180312&psc=1)
- Utilizando UML e Padrões: Uma Introdução à Análise e ao Projeto Orientados a Objetos e ao Desenvolvimento Iterativo. À venda na [Amazon](https://www.amazon.com.br/Utilizando-UML-Padr%C3%B5es-Introdu%C3%A7%C3%A3o-Desenvolvimento-ebook/dp/B016V9PZXA)
```

Renderiza assim:

- Entendendo Algoritmos: Um Guia Ilustrado Para Programadores e Outros Curiosos. À venda na [Amazon](https://www.amazon.com.br/Entendendo-Algoritmos-Ilustrado-Programadores-Curiosos/dp/8575225634)
- Algoritmos - Teoria e Prática. À venda na [Amazon](https://www.amazon.com.br/Algoritmos-Teoria-Pr%C3%A1tica-Thomas-Cormen/dp/8535236996/ref=asc_df_8535236996/?tag=googleshopp00-20&linkCode=df0&hvadid=379707181411&hvpos=&hvnetw=g&hvrand=13813726138626692774&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9047717&hvtargid=pla-1002925180312&psc=1)
- Utilizando UML e Padrões: Uma Introdução à Análise e ao Projeto Orientados a Objetos e ao Desenvolvimento Iterativo. À venda na [Amazon](https://www.amazon.com.br/Utilizando-UML-Padr%C3%B5es-Introdu%C3%A7%C3%A3o-Desenvolvimento-ebook/dp/B016V9PZXA)

2023-05-08 00:19 UTC, italo-mauricio commented
Pronto jeff, pode sim fazer a alteração na branch local.

2023-06-10 00:36 UTC, mateusrovedaa commented
@italo-mauricio consegue ajustar para markdown ao invés de HTML?

2023-06-10 01:40 UTC, italo-mauricio reviewed
Passei tudo para markdown

2023-06-10 01:41 UTC, italo-mauricio commented
pronto mestre, passei tudo para markdown

Em sex., 9 de jun. de 2023 às 21:36, Mateus Roveda ***@***.***>
escreveu:

> @italo-mauricio <https://github.com/italo-mauricio> consegue ajustar para
> markdown ao invés de HTML?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Universidade-Livre/ciencia-da-computacao/pull/62#issuecomment-1585308256>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZINKNW2LFCU7VRYPKBY3O3XKO6RFANCNFSM6AAAAAAXFOGIMA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-17 14:36 UTC, Camilotk commented
Alguns links aparentemente possuem valores GET para referral e/ou affiliate. Remova todos tudo dos `?` para frente nos links para que possamos aprová-los.

2023-06-17 14:40 UTC, Camilotk requested changes

2023-06-17 14:40 UTC, Camilotk commented on extras/books.md
> +1 - [Entendendo Algoritmos: Um Guia Ilustrado Para Programadores e Outros Curiosos](https://www.amazon.com.br/Algoritmos-Teoria-Pr%C3%A1tica-Thomas-Cormen/dp/8535236996/ref=asc_df_8535236996/?tag=goo
Por exemplo, este deveria ser `https://www.amazon.com.br/Algoritmos-Teoria-Pr%C3%A1tica-Thomas-Cormen/dp/8535236996`.

O restante do link, ou seja `/ref=asc_df_8535236996/?tag=googleshopp00-20&linkCode=df0&hvadid=379707181411&hvpos=&hvnetw=g&hvrand=13813726138626692774&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9047717&hvtargid=pla-1002925180312&psc=1` são metadados de tracking.

2023-06-17 14:40 UTC, Camilotk commented on extras/books.md
> +10 - [Pense em Python: Pense Como um Cientista da Computação](https://www.amazon.com.br/Pense-Python-Como-Cientista-Computa%C3%A7%C3%A3o/dp/8575225081/ref=asc_df_8575225081/?tag=googleshopp00-20&link
Aqui também.

2023-06-17 14:40 UTC, Camilotk commented on extras/books.md
> +15 - [O codificador limpo: Um código de conduta para programadores profissionais](https://www.amazon.com.br/dp/8576086476/ref=sspa_dk_detail_1?psc=1&pd_rd_i=8576086476&pd_rd_w=MycdE&content-id=amzn1.
Aqui também.

2023-06-20 14:19 UTC, jeffque commented on extras/books.md
> +1 - [Entendendo Algoritmos: Um Guia Ilustrado Para Programadores e Outros Curiosos](https://www.amazon.com.br/Algoritmos-Teoria-Pr%C3%A1tica-Thomas-Cormen/dp/8535236996/ref=asc_df_8535236996/?tag=goo
```suggestion
1 - [Entendendo Algoritmos: Um Guia Ilustrado Para Programadores e Outros Curiosos](https://www.amazon.com.br/Algoritmos-Teoria-Pr%C3%A1tica-Thomas-Cormen/dp/8535236996)
```

2023-06-20 14:22 UTC, jeffque commented on extras/books.md
> +15 - [O codificador limpo: Um código de conduta para programadores profissionais](https://www.amazon.com.br/dp/8576086476/ref=sspa_dk_detail_1?psc=1&pd_rd_i=8576086476&pd_rd_w=MycdE&content-id=amzn1.
```suggestion
1 - [Entendendo Algoritmos: Um Guia Ilustrado Para Programadores e Outros Curiosos](https://www.amazon.com.br/Algoritmos-Teoria-Pr%C3%A1tica-Thomas-Cormen/dp/8535236996/)

2 - [Algoritmos - Teoria e Prática](https://www.amazon.com.br/Utilizando-UML-Padr%C3%B5es-Introdu%C3%A7%C3%A3o-Desenvolvimento-ebook/dp/B016V9PZXA)

3 - [Utilizando UML e Padrões: Uma Introdução à Análise e ao Projeto Orientados a Objetos e ao Desenvolvimento Iterativo](https://www.amazon.com.br/Utilizando-UML-Padr%C3%B5es-Introdu%C3%A7%C3%A3o-Desenvolvimento-ebook/dp/B016V9PZXA)

4 - [Código limpo: Habilidades práticas do Agile Software](https://www.amazon.com.br/C%C3%B3digo-limpo-Robert-C-Martin/dp/8576082675)

5 - [Engenharia de Software: Uma Abordagem Profissional](https://www.amazon.com.br/Engenharia-Software-Uma-Abordagem-Profissional/dp/8580555337)

6 - [Redes de computadores e a Internet](https://www.amazon.com.br/Redes-computadores-Internet-James-Kurose/dp/8582605587)

7 - [Introdução à ciência da computação](https://www.amazon.com.br/Introdu%C3%A7%C3%A3o-ci%C3%AAncia-computa%C3%A7%C3%A3o-Ricardo-Fedeli/dp/8522108455)

8 - [Matemática Discreta e Suas Aplicações](https://www.amazon.com.br/Matem%C3%A1tica-Discreta-Aplica%C3%A7%C3%B5es-Kenneth-Rosen/dp/8577260364)

9 - [Introdução à Programação com Python: Algoritmos e Lógica de Programação Para Iniciantes](https://www.amazon.com.br/Introdu%C3%A7%C3%A3o-Programa%C3%A7%C3%A3o-com-Python-Algoritmos/dp/8575227181)

10 - [Pense em Python: Pense Como um Cientista da Computação](https://www.amazon.com.br/Pense-Python-Como-Cientista-Computa%C3%A7%C3%A3o/dp/8575225081)

11 - [Artificial Intelligence: A Modern Approach](https://www.amazon.com.br/Artificial-Intelligence-Approach-Stuart-Russell/dp/0134610997)

12 - [Data science para negócios: O que você precisa saber sobre mineração de dados e pensamento analítico de dados](https://www.amazon.com.br/Data-Science-para-neg%C3%B3cios-Fawcett/dp/8576089726)

13 - [Grafos: Teoria, Modelos, Algoritmos](https://www.amazon.com.br/Data-Science-para-neg%C3%B3cios-Fawcett/dp/8576089726)

14 - [Problemas Clássicos de Ciência da Computação com Python](https://www.amazon.com.br/Data-Science-para-neg%C3%B3cios-Fawcett/dp/8576089726)

15 - [O codificador limpo: Um código de conduta para programadores profissionais](https://www.amazon.com.br/dp/8576086476)
```

2023-06-20 14:23 UTC, jeffque commented on extras/books.md
> +1 - [Entendendo Algoritmos: Um Guia Ilustrado Para Programadores e Outros Curiosos](https://www.amazon.com.br/Algoritmos-Teoria-Pr%C3%A1tica-Thomas-Cormen/dp/8535236996/ref=asc_df_8535236996/?tag=goo
Feito

2023-06-20 14:24 UTC, jeffque commented on extras/books.md
> +10 - [Pense em Python: Pense Como um Cientista da Computação](https://www.amazon.com.br/Pense-Python-Como-Cientista-Computa%C3%A7%C3%A3o/dp/8575225081/ref=asc_df_8575225081/?tag=googleshopp00-20&link
Feito

2023-06-20 14:24 UTC, jeffque commented on extras/books.md
> +15 - [O codificador limpo: Um código de conduta para programadores profissionais](https://www.amazon.com.br/dp/8576086476/ref=sspa_dk_detail_1?psc=1&pd_rd_i=8576086476&pd_rd_w=MycdE&content-id=amzn1.
Feito

2023-07-28 21:34 UTC, Camilotk approved these changes

2023-07-28 21:34 UTC, Camilotk commented
Revisado novamente, parece tudo certo! 👍🏼 

Muito obrigado @jeffque e @italo-mauricio! 💯

2023-07-28 21:34 UTC, merged