Create certification.md
Universidade-Livre/ciencia-da-computacao pull request #76
Opened 2023-09-05 16:54 UTC by CarlosEduardoLemos

Criação e adicionando certificações Gratuitas

2024-03-11 19:56 UTC, JakelineWeschenfelder commented
Super bacana o projeto

2024-09-16 14:55 UTC, mateusrovedaa requested changes
Deixei alguns comentários. Muito obrigado pelas contribuições!

2024-09-16 14:55 UTC, mateusrovedaa commented on README.md
> +[Bancos de Dados MYSQL - Curso em Vídeo](https://www.cursoemvideo.com/curso/mysql/) | 4 Semanas | 3 horas/semana | MER; Projeto de Banco de Dados; Normalização; SQL. | - | -
Apenas alterar o nome para MySQL

2024-09-16 14:55 UTC, mateusrovedaa commented on README.md
> +[CyberSecurity](https://github.com/CarlosEduardoLemos/ciencia-da-computacao/blob/main/specializations/cybersecurity.md) | 20+ semanas | Média de  4 h/semana | `segurança`, `pentest`, `criptografia`,
O link precisa apontar para o repositório da UBL.

2024-09-16 14:55 UTC, mateusrovedaa commented on certification/certification.md
> +# Certificações Profissionais
Acredito que isso poderia estar dentro da pasta extras

2024-09-16 14:55 UTC, mateusrovedaa commented on specializations/cybersecurity.md
> +Para se destacar na área de Segurança da Informação e combater as ameaças digitais, é fundamental ir além da teoria. O site [PortSwigger](https://portswigger.net/) oferece treinamento gratuito em tes
Acredito que esse trecho não é necessário estar aqui.

2024-09-16 14:55 UTC, mateusrovedaa commented on specializations/web_development.md
> +[HTML e CSS, Parte III](https://www.cursoemvideo.com/curso/curso-html5-e-css3-modulo-4-de-5-40-horas/) | 2 Semanas | 3 horas/semana | iframes; Media Queries;
Alterar para parte 4

2024-09-19 01:31 UTC, mateusrovedaa commented
Estou fechando a PR pois a versão do README utilizada é muito antiga. Faça uma nova PR com as contribuições.

2024-09-19 01:31 UTC, closed without merging